name: xlist
description: Xlist project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: '3.32.5'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any

  video_player: any
  video_player_web: any
  video_player_android: any
  video_player_avfoundation: any

  get: any
  get_storage: any
  dio: any
  path: any
  floor: any
  jiffy: any
  crypto: any
  encrypt: any
  keframe: any
  charset: any
  wakelock_plus: any
  audio_wave: any
  share_plus: any
  photo_view: any
  file_picker: any
  url_launcher: any
  image_picker: any
  easy_refresh: any
  infinite_scroll_pagination: ^4.0.0
  toggle_switch: any
  vivysub_utils: any
  path_provider: any
  in_app_review: any
  audio_service: any
  code_text_field: any
  adaptive_dialog: any
  dismissible_page: any
  pull_down_button: any
  device_info_plus: any
  flex_color_scheme: any
  package_info_plus: any
  permission_handler: any
  modal_bottom_sheet: any
  image_gallery_saver: any
  font_awesome_flutter: any
  cached_network_image: any
  subtitle_wrapper_package: any
  syncfusion_flutter_pdfviewer: any
  flutter_svg: any
  flutter_phoenix: any
  flutter_slidable: any
  flutter_screenutil: any
  flutter_smart_dialog: any
  flutter_inappwebview: any
  flutter_native_splash: any
  flutter_keyboard_visibility: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen: any
  flutter_lints: any
  floor_generator: any
  flutter_launcher_icons: any
  change_app_package_name: any
  build_runner: any
  json_model: any
  json_serializable: any

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  image: assets/common/logo-transparent.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#121212"
    image: assets/common/logo-transparent.png

flutter_app_name:
  name: "CloudX"

flutter_gen:
  output: lib/gen/
  line_length: 80

flutter_icons:
  web:
    generate: true
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/common/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/common/
    - assets/images/
