name: xlist
description: Xlist project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <4.0.0'
  flutter: '>=1.12.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  video_player: ^2.8.6 # 替换 fijkplayer
  video_player_web: ^2.3.1
  video_player_android: ^2.4.16
  video_player_avfoundation: ^2.6.1

  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.0.1
  path: ^1.8.2
  floor: ^1.4.2
  jiffy: ^6.1.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  keframe: ^3.0.0
  charset: ^2.0.1
  wakelock_plus: ^1.1.8 # 替换 wakelock
  audio_wave: ^0.1.5
  share_plus: ^11.0.0
  photo_view: ^0.15.0
  file_picker: ^10.2.0
  url_launcher: ^6.1.11
  image_picker: ^1.1.2
  easy_refresh: ^3.3.1+2
  infinite_scroll_pagination: ^4.0.0 # 添加无限滚动分页
  toggle_switch: ^2.1.0
  vivysub_utils: ^0.2.0
  path_provider: ^2.0.15
  in_app_review: ^2.0.6
  audio_service: ^0.18.10
  code_text_field: ^1.1.0
  adaptive_dialog: ^2.1.0
  dismissible_page: ^1.0.1
  pull_down_button: ^0.10.2
  device_info_plus: ^11.0.0
  flex_color_scheme: ^8.2.0
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.1
  modal_bottom_sheet: ^3.0.0-pre
  image_gallery_saver: ^2.0.3
  font_awesome_flutter: ^10.4.0
  cached_network_image: ^3.2.3
  subtitle_wrapper_package: ^2.1.1
  syncfusion_flutter_pdfviewer: ^20.4.54
  flutter_svg: ^2.0.5
  flutter_phoenix: ^1.1.0
  flutter_slidable: ^4.0.0
  flutter_screenutil: ^5.6.0
  flutter_downloader: ^1.10.2
  flutter_smart_dialog: ^4.7.1
  flutter_inappwebview: ^6.0.0
  flutter_native_splash: ^2.2.19
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen: ^5.2.0
  flutter_lints: ^6.0.0
  floor_generator: ^1.4.2
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.1.0
  build_runner: ^2.4.0
  json_model: ^1.0.0 # 保持不变，因为没有明确的更新需求
  json_serializable: ^6.8.0

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  image: assets/common/logo-transparent.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#121212"
    image: assets/common/logo-transparent.png

flutter_app_name:
  name: "Xlist"

flutter_gen:
  output: lib/gen/
  line_length: 80

flutter_icons:
  web:
    generate: true
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/common/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/common/
    - assets/images/